#!/usr/bin/env bash
# amps-connectors-compose.sh -- run the config tree's connector applications with podman compose.
#
# The compose file is GENERATED from config/<env>/<flow>/<app-name>/: the tree is the single
# source of truth, so adding application #51 is `mkdir` + one application.yml -- no compose
# editing. One service per app directory; each flow is a compose profile, so a slice of the
# fleet starts with `up <flow>` and nobody starts fifty JVMs by accident.
#
#   scripts/amps-connectors-compose.sh local up streams    # just the streams flow's apps
#   scripts/amps-connectors-compose.sh local up            # every flow in local
#   scripts/amps-connectors-compose.sh local ps
#   scripts/amps-connectors-compose.sh local logs ticks-tcp
#   scripts/amps-connectors-compose.sh local down
#
# Each service runs image localhost/amps-connector-app:local -- or localhost/amps-<app>:local
# when apps/<app>/ exists (a custom-code application) -- with its two config directories
# mounted read-only. Build the images first: scripts/amps-connectors-compose.sh local build.
#
# The generated services publish NO ports (connectors are outbound clients; the actuator
# healthcheck runs inside the container network) with one exception: a connector configured
# with `tcp.mode: LISTEN` is dialled BY its feed, so set TCP_LISTEN_PORT to publish it.
# Sources and AMPS are reached on the host through host.containers.internal. Override per
# invocation:
#   AMPS_HOST / AMPS_PORT        the AMPS the containers publish into (default
#                                host.containers.internal:9007)
#   KAFKA_HOST / TCP_HOST /      the same, for the kafka, raw-socket (CONNECT mode), jdbc
#   JDBC_HOST / HAZELCAST_HOST   and hazelcast sources
#   JDBC_PASSWORD               the one credential the tree names and never writes
#   TCP_LISTEN_PORT             publish this container port on the host, for LISTEN feeds
#   IMAGE_TAG                   image tag (default local)
#   AMPS_CONNECTOR_MEM          per-container memory limit (default 384m; the JVM sizes
#                               itself from it via container awareness)
#   PODMAN                      container tool (default podman)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"                    # amps-connectors/
GRADLE_ROOT="$(dirname "$ROOT")"                   # the gradle build root
PODMAN="${PODMAN:-podman}"

usage() {
    sed -n '2,38p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 1
}

[ $# -ge 2 ] || usage
ENV_NAME="$1"; shift
CMD="$1"; shift
ENV_DIR="$ROOT/config/$ENV_NAME"
[ -d "$ENV_DIR" ] || { echo "no such environment: $ENV_DIR" >&2; exit 1; }
OUT="$ROOT/build/compose/amps-connectors-$ENV_NAME.yml"
PROJECT="amps-connectors-$ENV_NAME"

# ---- discovery -----------------------------------------------------------------

flows() {
    find "$ENV_DIR" -mindepth 1 -maxdepth 1 -type d ! -name common -exec basename {} \; | sort
}

apps_in() { # flow -> app names
    find "$ENV_DIR/$1" -mindepth 2 -maxdepth 2 -name application.yml \
        -exec dirname {} \; | xargs -n1 basename | sort
}

image_for() { # app -> image repository
    if [ -d "$ROOT/apps/$1" ]; then echo "amps-$1"; else echo "amps-connector-app"; fi
}

# ---- generation ----------------------------------------------------------------

generate() {
    mkdir -p "$(dirname "$OUT")"
    {
        echo "# GENERATED by scripts/amps-connectors-compose.sh from config/$ENV_NAME/ — do not edit."
        echo "name: $PROJECT"
        echo
        echo "services:"
        local flow app image
        for flow in $(flows); do
            for app in $(apps_in "$flow"); do
                image="$(image_for "$app")"
                cat <<SERVICE
  $app:
    image: localhost/$image:\${IMAGE_TAG:-local}
    profiles: ["$flow"]
    environment:
      SPRING_APPLICATION_NAME: $app
      AMPS_HOST: \${AMPS_HOST:-host.containers.internal}
      AMPS_PORT: \${AMPS_PORT:-9007}
      KAFKA_HOST: \${KAFKA_HOST:-host.containers.internal}
      TCP_HOST: \${TCP_HOST:-host.containers.internal}
      JDBC_HOST: \${JDBC_HOST:-host.containers.internal}
      JDBC_PASSWORD: \${JDBC_PASSWORD:-}
      HAZELCAST_HOST: \${HAZELCAST_HOST:-host.containers.internal}
    volumes:
      - $ENV_DIR/common:/app/config/common:ro
      - $ENV_DIR/$flow/$app:/app/config/instance:ro
    mem_limit: \${AMPS_CONNECTOR_MEM:-384m}
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health/readiness | grep -q UP"]
      interval: 15s
      timeout: 3s
      retries: 20
      start_period: 30s
SERVICE
                # A LISTEN connector is dialled by its feed, so it is the one kind of app
                # with something to publish. Opt in per invocation: the port belongs to one
                # app, and two apps publishing the same one would not start.
                if [ -n "${TCP_LISTEN_PORT:-}" ] \
                    && grep -q 'mode: *LISTEN' "$ENV_DIR/$flow/$app/application.yml"; then
                    cat <<PORTS
    ports:
      - "${TCP_LISTEN_PORT}:${TCP_LISTEN_PORT}"
PORTS
                fi
            done
        done
    } > "$OUT"
    echo "generated $OUT" >&2
}

compose() { # [profiles...] -- args...
    local profile_args=()
    while [ $# -gt 0 ] && [ "$1" != "--" ]; do
        profile_args+=(--profile "$1"); shift
    done
    shift
    "$PODMAN" compose -f "$OUT" "${profile_args[@]}" "$@"
}

# ---- commands ------------------------------------------------------------------

case "$CMD" in
    gen)
        generate
        ;;
    list)
        for flow in $(flows); do
            for app in $(apps_in "$flow"); do
                printf '%s/%s/%s  (localhost/%s)\n' \
                    "$ENV_NAME" "$flow" "$app" "$(image_for "$app")"
            done
        done
        ;;
    build)
        cd "$GRADLE_ROOT"
        tasks=(":amps-connectors:connector-app:dockerBuildLocal")
        for d in "$ROOT"/apps/*/; do
            [ -f "$d/build.gradle.kts" ] && tasks+=(":amps-connectors:apps:$(basename "$d"):dockerBuildLocal")
        done
        ./gradlew "${tasks[@]}"
        ;;
    up)
        generate
        # No flows named = every flow; each named flow activates its profile.
        if [ $# -eq 0 ]; then set -- $(flows); fi
        compose "$@" -- up -d
        compose "$@" -- ps
        ;;
    down|ps|stop|start|restart|logs|config)
        [ -f "$OUT" ] || generate
        compose $(flows) -- "$CMD" "$@"
        ;;
    *)
        usage
        ;;
esac
